### ISSUE TITLE
Persist state to flash memory

### ISSUE THREAD

**Issue by chriskiefer** [Emute-Lab-Instruments/uSEQ#50]
3 functions

**(save)** 

Saves the LISP environment in human readable format to flash memory

**(restore)** 

Automatically called on startup

**(save-usb)**

Send state down the wire for saving in another place 

Notes: philhower EPROM only reserves 4kb, can we expand this?

Expts:
1. save and restore string to eprom
2. save env to string
3. restore env from string
4. Add above functions
5. Expand storage

**Comment by monkey-w1n5t0n** [comment]
> Saves the LISP environment in human readable format to flash memory

Human-readable can mean a couple of different things here:
1) The raw (user-provided) code that created the environment in the first place and can fully recreate it:
```lisp
(def a 1)
(def b (+ a 2))
```
Pros: 
- looks exactly like what the user saved (and can also maintain comments, which may be very important to the user)
- code can be stored entirely in the module and sent to any number of editors to instantly reflect what's going on
- is immediately hackable upon boot
- _may_ be more space-efficient (TBD via testing)

Cons:
- Requires cache management (i.e. keeping track of the latest block of code that was used to define a symbol)
- Requires parsing and interpreting the code into a full Environment object (which will slow down boot, but only needs to happen once per restoration)

2) The raw serialisation of the environment (which is a map of symbols->values), formatted in e.g. JSON:
```
{
  "a": 1,
  "b": 3
}
```
Pros: 
- Is easier to code (there's already an `Environment::toString()` method, just needs to be made to recurse through parent/child envs)

Cons:
- Only stores pairs of symbol->value, which doesn't retain the relationships between variables that were known at definition time. In the above example, the information that "b" is meant to be `a + 2` is lost.
- It's lossy, i.e. doesn't maintain original code (including formatting, comments, etc) 
- Needs an additional de-serialiser method (as opposed to just passing the saved code string to `eval`)

> Notes: philhower EPROM only reserves 4kb, can we expand this?

This is being determined [here](https://github.com/earlephilhower/arduino-pico/blob/ea8874037c3027385d64fbdb89842291e9e34c61/libraries/EEPROM/src/EEPROM.cpp#L44) in the arduino-pico library, with a simple clamp of the requested size to [0,4096]. At first glance it seems that we can just remove this clamp and then request as much as we want, but need to make sure that the rest of the library doesn't assume that the size will never be over 4k.
