### ISSUE TITLE
add phase shift function

### ISSUE THREAD

**Issue by chriskiefer** [Emute-Lab-Instruments/uSEQ#75]
(defun phase (ph shift) (% (+ ph shift) 1.0))

**Comment by monkey-w1n5t0n** [comment]
Although they work slightly differently, I've added an `offset` function that offsets an entire expression in time, so we can achieve similar results with it.

For example:
```
(define my-phasor bar)
(a1 my-phasor)
(a2 (offset (/ barDur 2) my-phasor))
```
makes the two outputs have a 50% phase difference.

A good name for the function you specified could be `phasor-offset` (or `offset-phasor`? It probably makes sense to pick a convention at some point and stick with it).

**Comment by chriskiefer** [comment]
this is called 'shift'
