### ISSUE TITLE
Speed up firmware with __not_in_flash_func

### ISSUE THREAD

**Issue by chriskiefer** [Emute-Lab-Instruments/uSEQ#78]
void __not_in_flash_func(dosomething)(void) {
}

q: does this pull in functions called from the parent function?

**Comment by monkey-w1n5t0n** [comment]
> q: does this pull in functions called from the parent function?

According to [this](https://github.com/raspberrypi/pico-sdk/issues/410#issuecomment-841300503) comment, it doesn't seem that the compiler automatically propagates that to other functions being called.

**Comment by monkey-w1n5t0n** [comment]
Attempted on eval, apply, and update_signals but doesn't seem to make much of a difference. Tabling for now.
