### ISSUE TITLE
fix 'seq' function

### ISSUE THREAD

**Issue by chriskiefer** [Emute-Lab-Instruments/uSEQ#95]
(a1 (fromList '(0 0.1 0.8) bar))
 is different from

(a1 (seq '(0 0.1 0.8) bar))

but should be the same

**Comment by monkey-w1n5t0n** [comment]
Was also fixed [here](https://github.com/Emute-Lab-Instruments/uSEQ/commit/50a0b09f17c0f945f6c9eb5aab9e129af57eacb4) by commenting out the implementation of seq in LispLibrary
